services:
  - type: web
    name: shadow-garden-bot
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PHONE_NUMBER
        sync: false
      - key: OWNER_LID
        sync: false
    autoDeploy: false
